required = [
  "github.com/benbjohnson/genesis",
  "github.com/go-bindata/go-bindata",
  "github.com/gobuffalo/packr",
  "github.com/rakyll/statik/fs",
]

[[constraint]]
  name = "github.com/benbjohnson/genesis"
  branch = "master"

[[constraint]]
  name = "github.com/go-bindata/go-bindata"
  branch = "master"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  branch = "master"

[[constraint]]
  name = "github.com/rakyll/statik"
  branch = "master"
