required = [
  "github.com/bcicen/grmon/agent",
  "github.com/google/gops/agent",
]

[[constraint]]
  name = "github.com/bcicen/grmon"
  branch = "master"

[[constraint]]
  name = "github.com/google/gops"
  branch = "master"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "github.com/bcicen/grmon"
  go-tests = false
  non-go = false
  unused-packages = false

[[prune.project]]
  name = "github.com/google/gops"
  go-tests = false
  non-go = false
  unused-packages = false
