required = [
  "github.com/bcicen/grmon/agent",
  "github.com/google/gops/agent",
]

[[constraint]]
  name = "github.com/bcicen/grmon"
  branch = "master"

[[constraint]]
  name = "github.com/google/gops"
  branch = "master"
