required = ["github.com/goph/emperror"]

[[constraint]]
  name = "github.com/goph/emperror"
  branch = "master"

[[constraint]]
  name = "github.com/juju/errors"
  branch = "master"

[[constraint]]
  name = "github.com/oxequa/grace"
  branch = "master"

[[override]]
  name = "github.com/pkg/errors"
  branch = "master"
