[[constraint]]
  name = "github.com/juju/errors"
  branch = "master"

[[constraint]]
  name = "github.com/oxequa/grace"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "github.com/juju/errors"
  go-tests = false
  non-go = false
  unused-packages = false

[[prune.project]]
  name = "github.com/oxequa/grace"
  go-tests = false
  non-go = false
  unused-packages = false

[[prune.project]]
  name = "github.com/pkg/errors"
  go-tests = false
  non-go = false
  unused-packages = false
