required = [
  "github.com/ghodss/yaml",
  "github.com/mailru/easyjson",
  "github.com/mitchellh/mapstructure",
  "gopkg.in/yaml.v2",
]

[[constraint]]
  name = "github.com/ghodss/yaml"
  branch = "master"

  [constraint.metadata]
  extend = "gopkg.in/yaml.v2"
  reason = "http://ghodss.com/2014/the-right-way-to-handle-yaml-in-golang/"
  tags   = "yaml, json"

[[constraint]]
  name = "github.com/mailru/easyjson"
  branch = "master"

  [constraint.metadata]
  tags = "json, code generation"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  branch = "master"

  [constraint.metadata]
  tags = "generic"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2"

  [constraint.metadata]
  tags = "yaml"
